ALTER TABLE "Topic"             ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Comment"           ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Vote"              ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Attachment"        ENABLE ROW LEVEL SECURITY;
ALTER TABLE "User"              ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Account"           ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Session"           ENABLE ROW LEVEL SECURITY;
ALTER TABLE "VerificationToken" ENABLE ROW LEVEL SECURITY;
